require("user.options")
require("user.keymaps")
-- require("user.leap")
require("user.flash")
require("user.catppuccin")
require("user.colorscheme")
require("user.neorg")
require("user.pets")
-- require("user.wilder")
require("user.image")
require("user.cmp")
require("user.lsp")
require("user.zen-mode")
require("user.telescope")
require("user.nvim-web-devicons")
require("user.treesitter")
require("user.autopairs")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
-- require("user.noice")
require("user.dashboard")
require("user.toggleterm")
require("user.trouble")
require("user.which-key")
-- require("user.lualine")
require("user.feline")
require("user.presence")
require("user.fidget")
-- require("user.copilot")
