require("user.options")
require("user.keymaps")
require("user.flash")
require("user.colorscheme")
-- require("user.neorg")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.nvim-web-devicons")
require("user.treesitter")
require("user.autopairs")
require("user.hover")
require("user.comment")
require("user.gitsigns")
require("user.nvim-tree")
require("user.bufferline")
require("user.dashboard")
require("user.toggleterm")
require("user.trouble")
require("user.which-key")
require("user.nvim-ufo")
require("user.lualine")
require("user.fidget")

-- ALWAYS KEEP THIS AT THE BOTTOM
require("colorizer").setup()
